### ISSUE TITLE
Not able to differentiate between charching and discharchching state

### ISSUE THREAD

**Issue by nachtmaar** [NeariX67/SmartBMSUtility#1]
It seems that for my battery (Liontron LifePo4 150Ah) the app cannot detect whether it is disgarching or charging.

The screenshot of the app was taken while charging via Solar, see first screenshot.

Let me know if you need more information.

![image](https://user-images.githubusercontent.com/8013145/103452536-f7d87a00-4cd0-11eb-9488-eaa582cf0652.png)

![image](https://user-images.githubusercontent.com/8013145/103452502-a16b3b80-4cd0-11eb-9ca3-fff655714570.png)

**Comment by NeariX67** [comment]
Ich seh schon. Da haut irgendwas nicht hin. Ich werde mir da mal in Sachen Frontend was ausdenken müssen. Ich arbeite zurzeit an der Configuration vom BMS, das hat erstmal als Version 1.1.0 vorrang. Ich denke das wird dann in Version 1.1.1 zusammen mit LifePo Support gefixt. Eine negative Leistung sollte eigentlich für entladung stehen, warum dann Peakpower bei 0.00 bleibt ist mir ein Rätsel. Ich teste das mal mit meinem Setup nachher.
----------English---------
Something isn't working right. I'm currently working on v1.1.0 that will allow bms configuration. I will fix this frontend issue in v1.1.1 together with LifePo support. Negative power should mean discharge, but the peakpower isn't updating for some reason. I'll take a look into it.

**Comment by nachtmaar** [comment]
Thank you! Let me know if you need need me to test the fixed version (via TestFlight).

**Comment by NeariX67** [comment]
Edit: Bei mir steht bei entladung ganz normal +80W und Peakpower geht auch. Hast du die andere BMS App installiert und kannst daraus mal ein Screenshot anhängen?
Seems to run normal for me. Both of my batteries report a positiv power while discharging. Maybe you accidently swapped your charging and discharging port of your BMS?
Could you try it with the App of Lukas Deszynski and see if it still shows that is it "charging"?
https://apps.apple.com/de/app/xiaoxiang-bms/id1375405426

**Comment by NeariX67** [comment]
Just watched your issue again and noticed the correct behavior. I thought you are discharging and it reports charging but taking a look at „remaining chargetime“ reveals that it is indeed charging like intended. Negative current and power means charging, positive current and power means discharging.

**Comment by nachtmaar** [comment]
Sure, here are the screenshots.

If the battery is charging, it is getting energy, hence the sign should be positive. Then discharging, you take energy from battery, hence it should be negative sign, don't you think so? All other apps have the sign like that.
I checked, then discharging it has indeed positive sign.

![image](https://user-images.githubusercontent.com/8013145/103458111-4a338e00-4d05-11eb-9595-50c24f27915a.png)![image](https://user-images.githubusercontent.com/8013145/103458112-4c95e800-4d05-11eb-972d-99675d15dcdc.png)

**Comment by NeariX67** [comment]
I'll invert the current reading and it will be available in version 1.1.0 (Coming soon™)

**Comment by NeariX67** [comment]
Hey, if you are interested, you can test the early beta of v1.1.0. It currently features a configuration page that allows reading (and writing soon) of parameters that your bms uses to protect your cells.
I might need your apple id to invite you for testing.
