### ISSUE TITLE
Brilliant app, a suggestion, a request and an error.

### ISSUE THREAD

**Issue by TheDodgersOnline** [NeariX67/SmartBMSUtility#10]
Hi
Just came across this app and it is great. Far better than the Xiaoxiang app floating around.
Suggestion - Charge $9.99 for this app. It is worth it. I am certainly going to recommend it.
Request - Is it possible to put he battery indication (85% Charging / Discharging ) on the main screen. For thos like me who have 
                 multiple batteries in use.
Error - When I select "GPS" THe app crashed and goes back to the iPad main screen. iPad Mini with IOS 14.4.2

Thanks and Regards
Richard

**Comment by NeariX67** [comment]
> Is it possible to put he battery indication (85% Charging / Discharging ) on the main screen
Well yes, but no.
I understood how the Xiaoxiang App 2.0 did it. And that is probably the only way to accomplish that. But I don't like the way it has been achieved.

Sadly, I don't have a iPad Mini laying around (the only other iPad doesn't crash for whatever reason) so it's nearly impossible for me to take a look into that issue. But at least now I know what I need to do to make the app crash.

Appreciate your feedback.
