### ISSUE TITLE
Empty device list

### ISSUE THREAD

**Issue by RasmusHJV2** [NeariX67/SmartBMSUtility#18]
When there is no devices in the device list, its pretty empty, idea could be to add some text saying "Couldn't find any devices in your area".

**Comment by NeariX67** [comment]
I can do that in v2

**Comment by RasmusHJV2** [comment]
Perfect! 😃

**Comment by northlandb** [comment]
I just opened the app and now I am seeing nothing in the device list, I would like to add my 16S JBD BMS to the compatibility if possible?

What do you need from me?

**Comment by NeariX67** [comment]
> I just opened the app and now I am seeing nothing in the device list, I would like to add my 16S JBD BMS to the compatibility if possible?
> 
> What do you need from me?

Thats weird. Could you please download the "BlueCap" App in the Apple App Store. Click Scan in the top left corner and search for your BMS in the device list and tap it. Click Services, take a screenshot and if "FF00 - Unknown" exists, tap that as well and screenshot that.

When did you buy this BMS?
