### ISSUE TITLE
Limit of 12 devices?

### ISSUE THREAD

**Issue by neoneddy** [NeariX67/SmartBMSUtility#22]
I have a number of these batteries in my shop.  Not all of them load in the list.  So far only 12 list.

**Comment by NeariX67** [comment]
There isn't a limit and i have no idea why it only lists 12 devices. Maybe it's caused by iOS itself. Are you sure that all devices are in range, compatible and had enough time to be discovered?

**Comment by neoneddy** [comment]
I should have clarified, this is on macOS .  If I pull-down enough times or restart the app I can get to the ID I want.

I have another app I use on my iOS device and that shows all of them.

**Comment by NeariX67** [comment]
Please re-open issue if this issue persists in version 3 (coming very soon)
