### ISSUE TITLE
MAC address Display

### ISSUE THREAD

**Issue by madmacks59** [NeariX67/SmartBMSUtility#24]
I have many BMS' and they all have names stored on them. When I launch the app I see a list of generic names which makes it difficult to connect to a target BMS. And the MAC addresses displayed on the tiles is microscopic so unusable to select.
![image](https://user-images.githubusercontent.com/48607370/211354155-0e1cbe0f-3867-4762-ae2d-f34707965826.png)

**Comment by NeariX67** [comment]
Yeah you're right, its unreadable and I did that intentionally for whatever reason. But I've not yet seen how to read the actual MAC-Address instead of using a random UUID (Identifier). I will change that, but don't know how right now

**Comment by madmacks59** [comment]
I wish I had the knowledge to help. My comments are just feedback and not criticism! I haven't done Swift programming but it's on my list of things to learn. I do do (ha I said Do Do) Arduino programming and am trying to build a device that sits connected all the time to a BMS using UART, reads various values, and then remotely logs that data to a MariaDB table on one of my Raspberry PIs. I have 5 separate battery systems and I want a central web page to view all their conditions in one place. Figuring out the API to read the values on the Arduino is a PITA...so I appreciate your efforts!

**Comment by madmacks59** [comment]
Yep, they show up...

![image](https://user-images.githubusercontent.com/48607370/211363079-5aba538a-76c7-4fbb-a0ac-84e87b7c72ff.jpeg)

**Comment by NeariX67** [comment]
Huh. They show up with the "wrong" names. So the other app stores the device name somewhere else, which I can't read and thus the other name shows up. My App works as expected in that case.

**Comment by madmacks59** [comment]
Looks like the "other all" show three places where name is used.
![image](https://user-images.githubusercontent.com/48607370/211401879-32446abc-49f4-4953-8cd8-40d886b8d142.jpeg)

And...

![image](https://user-images.githubusercontent.com/48607370/211401913-9e75a8eb-040a-4538-8b3d-c75910618b91.jpeg)

"BMS Alias" appears to be app specific (ie not on the BMS).
"BMS Bluetooth Name" I'd think is on the BMS and should be available to applications.
"PIN/BMS Name" appears to be what your app is pulling. Maybe you can access the "BMS Bluetooth Name" as the "PIN" version, as I understand the manufacturers info should not be changed.

**Comment by NeariX67** [comment]
Even though the name is properly set in BMS Bluetooth name, the BLE Scanner still shows "xiaoxiang BMS" and therefore that's the name my app displays. Try setting the name(s) again with the other app.

**Comment by NeariX67** [comment]
Btw, you can also set a custom name for your BMS' in the settings of a device.
![image](https://user-images.githubusercontent.com/31779313/211406979-0612ca0e-fbed-48a7-8d3b-56ebc31767b8.png)
