### ISSUE TITLE
Not reading the configured battery size.

### ISSUE THREAD

**Issue by madmacks59** [NeariX67/SmartBMSUtility#25]
When I select what I think is the target BMS (see other issue I raised) the app displays an incorrect value for the AHs if the battery.

Display from factory app...
![image](https://user-images.githubusercontent.com/48607370/211354627-3f2e627c-b785-4ee1-82f0-71a4ba6e0462.png)

Display from this app...
![image](https://user-images.githubusercontent.com/48607370/211354753-f998f6bf-fd5d-46e9-a678-2c7da3ccfe50.png)

**Comment by NeariX67** [comment]
Seeing that the capacity values are below zero, i think the capacity is larger than what can be stored in whatever variable type i used. I hope using a better variable type would fix that. I'll make some tests and release a fix.

**Comment by NeariX67** [comment]
Can you download 'BLE Scanner' from the appstore and tell me whether your BMS' are showing up with the correct names?
![image](https://user-images.githubusercontent.com/31779313/211357914-0056b865-1bc1-47f7-8a58-330dd2f09015.jpeg)

**Comment by NeariX67** [comment]
Fixed. New testflight version very soon.
