### ISSUE TITLE
Bluetooth trouble

### ISSUE THREAD

**Issue by floreno** [NeariX67/SmartBMSUtility#38]
When i start the app in Mac OS X 12.6.5 on a MacBook Air i get the following message "Blootooth ist nicht authorisiert.". No connection possible.

**Comment by NeariX67** [comment]
This is because you have denied bluetooth access for our app. To allow it, go to system preferences -> Security and Privacy -> Bluetooth -> Enable SmartBMS Utility

**Comment by floreno** [comment]
Thanks!
The proper path was: system preferences -> Security and Privacy -> **Privacy** -> Bluetooth -> Enable SmartBMS Utility
